Update/sec 38
Newforma/Newforma-inc-security-policy-procedures pull request #8
Opened 2021-09-28 14:38 UTC by Jkinville

Finished vendor policy. Also updated email in continuity policy to one we control.

2021-09-28 23:10 UTC, kellyuehling requested changes
Will the date on line 17 be updated when the actual doc is approved?
Several spelling errors in 2.3.5 - Line 96.

2021-09-28 23:11 UTC, kellyuehling approved these changes

2021-10-06 16:03 UTC, Jkinville commented
> Will the date on line 17 be updated when the actual doc is approved? Several spelling errors in 2.3.5 - Line 96.

Yeah, I plan to update it before merge. Those spelling errors have been fixed. Ironically, those are from the original doc so they have been missed since 2015.

2021-10-06 17:41 UTC, kellyuehling approved these changes

2021-10-06 18:19 UTC, merged